name: Build Python App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GLOBAL_MESSAGE: 'Hi'
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -c "print(f'{env.GLOBAL_MESSAGE}')"

  greet:
    runs-on: ubuntu-latest
    env:
      GREETING_MESSAGE: 'Hi World'
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -c "print(f'{env.GREETING_MESSAGE}')"
