name: Build Python App
on: push
env:
  GLOBAL_MESSAGE: Hi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -c "print('${GLOBAL_MESSAGE}')"

  greet:
    runs-on: ubuntu-latest
    env:
      GREETING_MESSAGE: Hi World
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: echo $GREETING_MESSAGE
